"""Export Kubernetes operator manifests for the lab spec.

Rather than half-managing kubectl lifecycles, searchlab emits the idiomatic
operator custom resource for each engine — the same knobs (version, nodes,
heap, GC flags) translated to the shape each operator expects:

  solr          -> SolrCloud CR       (Apache Solr Operator)
  elasticsearch -> Elasticsearch CR   (Elastic Cloud on Kubernetes, ECK)
  opensearch    -> OpenSearchCluster  (OpenSearch Operator)

`searchlab k8s > lab.yaml && kubectl apply -f lab.yaml` after installing the
relevant operator; the header comment in each manifest says which and how.
"""

from __future__ import annotations

import yaml

from .cluster import ClusterSpec

_HINTS = {
    "solr": (
        "# Requires the Apache Solr Operator:\n"
        "#   helm repo add apache-solr https://solr.apache.org/charts\n"
        "#   helm install solr-operator apache-solr/solr-operator\n"
    ),
    "elasticsearch": (
        "# Requires ECK (Elastic Cloud on Kubernetes):\n"
        "#   kubectl create -f https://download.elastic.co/downloads/eck/2.13.0/crds.yaml\n"
        "#   kubectl apply -f https://download.elastic.co/downloads/eck/2.13.0/operator.yaml\n"
    ),
    "opensearch": (
        "# Requires the OpenSearch Operator:\n"
        "#   helm repo add opensearch-operator https://opensearch-project.github.io/opensearch-k8s-operator/\n"
        "#   helm install opensearch-operator opensearch-operator/opensearch-operator\n"
    ),
}


def _java_opts(spec: ClusterSpec) -> str:
    opts = f"-Xms{spec.heap} -Xmx{spec.heap}"
    if spec.gc_tune:
        opts += f" {spec.gc_tune}"
    return opts


def _solr_cr(spec: ClusterSpec) -> dict:
    cr: dict = {
        "apiVersion": "solr.apache.org/v1beta1",
        "kind": "SolrCloud",
        "metadata": {"name": spec.project_name},
        "spec": {
            "replicas": spec.solr_nodes,
            "solrImage": {"repository": "solr", "tag": spec.solr_version},
            "solrJavaMem": f"-Xms{spec.heap} -Xmx{spec.heap}",
            "zookeeperRef": {"provided": {"replicas": spec.zk_nodes}},
        },
    }
    opts = " ".join(x for x in (spec.gc_tune, spec.solr_opts) if x)
    if opts:
        cr["spec"]["solrOpts"] = opts
    return cr


def _es_cr(spec: ClusterSpec) -> dict:
    return {
        "apiVersion": "elasticsearch.k8s.elastic.co/v1",
        "kind": "Elasticsearch",
        "metadata": {"name": spec.project_name},
        "spec": {
            "version": spec.solr_version,
            # lab cluster: skip TLS/auth ceremony, mirror the compose setup
            "http": {"tls": {"selfSignedCertificate": {"disabled": True}}},
            "nodeSets": [{
                "name": "default",
                "count": spec.solr_nodes,
                "config": {"xpack.security.enabled": False},
                "podTemplate": {"spec": {"containers": [{
                    "name": "elasticsearch",
                    "env": [{"name": "ES_JAVA_OPTS", "value": _java_opts(spec)}],
                }]}},
            }],
        },
    }


def _os_cr(spec: ClusterSpec) -> dict:
    return {
        "apiVersion": "opensearch.opster.io/v1",
        "kind": "OpenSearchCluster",
        "metadata": {"name": spec.project_name},
        "spec": {
            "general": {
                "version": spec.solr_version,
                "serviceName": spec.project_name,
                "httpPort": 9200,
            },
            "security": {"tls": {"transport": {"generate": True},
                                 "http": {"generate": True}}},
            "nodePools": [{
                "component": "nodes",
                "replicas": spec.solr_nodes,
                "roles": ["cluster_manager", "data"],
                "jvm": _java_opts(spec),
            }],
        },
    }


def render_k8s(spec: ClusterSpec) -> str:
    cr = {"solr": _solr_cr, "elasticsearch": _es_cr, "opensearch": _os_cr}[spec.engine](spec)
    return (
        f"# Generated by searchlab (engine={spec.engine}, {spec.solr_nodes} node(s), "
        f"heap {spec.heap})\n"
        + _HINTS[spec.engine]
        + yaml.safe_dump(cr, sort_keys=False)
    )
