"""Tests for k8s manifest export and GC HTML reports."""

from __future__ import annotations

import yaml
from click.testing import CliRunner

from searchlab.cli import main
from searchlab.cluster import ClusterSpec
from searchlab.gclog import Pause, find_gclogs
from searchlab.k8s import render_k8s
from searchlab.report import html_gc


def _docs(spec):
    text = render_k8s(spec)
    assert text.startswith("# Generated by searchlab")
    return yaml.safe_load(text)


def test_k8s_solr_cr():
    cr = _docs(ClusterSpec(solr_nodes=3, zk_nodes=3, heap="2g",
                           gc_tune="-XX:+UseZGC", solr_opts="-Dfoo=1"))
    assert cr["kind"] == "SolrCloud"
    assert cr["spec"]["replicas"] == 3
    assert cr["spec"]["solrImage"]["tag"] == "9.6"
    assert cr["spec"]["solrJavaMem"] == "-Xms2g -Xmx2g"
    assert cr["spec"]["zookeeperRef"]["provided"]["replicas"] == 3
    assert "-XX:+UseZGC" in cr["spec"]["solrOpts"] and "-Dfoo=1" in cr["spec"]["solrOpts"]


def test_k8s_es_cr():
    cr = _docs(ClusterSpec(engine="elasticsearch", solr_version="8.14.3",
                           solr_nodes=2, heap="1g"))
    assert cr["kind"] == "Elasticsearch"
    ns = cr["spec"]["nodeSets"][0]
    assert ns["count"] == 2
    assert ns["config"]["xpack.security.enabled"] is False
    env = ns["podTemplate"]["spec"]["containers"][0]["env"][0]
    assert env["name"] == "ES_JAVA_OPTS" and "-Xmx1g" in env["value"]
    assert cr["spec"]["http"]["tls"]["selfSignedCertificate"]["disabled"] is True


def test_k8s_os_cr():
    cr = _docs(ClusterSpec(engine="opensearch", solr_version="2.15.0",
                           solr_nodes=3, heap="2g", gc_tune="-XX:+UseG1GC"))
    assert cr["kind"] == "OpenSearchCluster"
    pool = cr["spec"]["nodePools"][0]
    assert pool["replicas"] == 3
    assert pool["jvm"] == "-Xms2g -Xmx2g -XX:+UseG1GC"
    assert cr["spec"]["general"]["version"] == "2.15.0"


def test_k8s_cli_flags_without_cluster(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)  # no .searchlab spec anywhere
    r = CliRunner().invoke(main, ["k8s", "--engine", "es", "--nodes", "5", "--heap", "4g"])
    assert r.exit_code == 0
    cr = yaml.safe_load(r.output)
    assert cr["kind"] == "Elasticsearch" and cr["spec"]["nodeSets"][0]["count"] == 5


def test_find_gclogs_es_pattern(tmp_path):
    d = tmp_path / "gc-logs" / "es1"
    d.mkdir(parents=True)
    (d / "gc.log").write_text("x")
    (d / "gc.log.0").write_text("x")
    logs = find_gclogs(tmp_path / "gc-logs")
    assert [p.name for p in logs["es1"]] == ["gc.log", "gc.log.0"]


def test_html_gc_report(tmp_path):
    pauses = [Pause(10 + i * 10, "Young", 12 + i, 380.0) for i in range(5)]
    pauses.append(Pause(45, "Full", 800.0, 600.0))
    out = tmp_path / "gc.html"
    html_gc({"solr1": sorted(pauses, key=lambda p: p.uptime_s)}, out)
    h = out.read_text()
    assert h.count("<svg") == 1
    assert "Full 800ms" in h                       # annotated Full marker
    assert h.count("<circle") == 6                 # 5 young dots + 1 full
    assert "throughput lost to GC" in h            # summary embedded
